# Generated by Django 4.0.6 on 2022-07-11 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contact_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_active',
        ),
    ]
