# Generated by Django 4.0.6 on 2022-07-11 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_register_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
    ]
